# Generated by Django 4.2.27 on 2026-03-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_coach_achievements_coach_coaching_philosophy_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        # Create Team model
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, help_text='Team name (e.g., U14 Boys Elite)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('age_group', models.CharField(max_length=20, help_text='e.g., U10, U12, U14')),
                ('skill_level', models.CharField(max_length=20, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite/Competitive')], default='intermediate')),
                ('club_name', models.CharField(max_length=100, blank=True)),
                ('description', models.TextField(blank=True, help_text='Team description and goals')),
                ('max_players', models.IntegerField(default=18, help_text='Maximum number of players on team')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Add team to Client model
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.team', related_name='managed_by'),
        ),
        # Add team to Player model
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.team', related_name='players'),
        ),
        # Add team many-to-many for coaches who can train this team
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(to='coaches.Coach', related_name='teams', blank=True),
        ),
        # Add team manager (client who manages the team)
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', related_name='managed_teams'),
        ),
    ]
