# Generated by Django 4.2.27 on 2025-12-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('basic4', 'Basic 4 - 4 classes / 4 weeks'), ('basic8', 'Basic 8 - 8 classes / 4 weeks'), ('elite24', 'Elite 24 - 24 classes / 12 weeks'), ('unlimited', 'Unlimited - 12 weeks')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sessions_included', models.IntegerField(help_text='Number of sessions included, 0 for unlimited')),
                ('validity_weeks', models.IntegerField(help_text='How many weeks the package is valid')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to say')], max_length=1)),
                ('soccer_club', models.CharField(blank=True, help_text='Current soccer club', max_length=100)),
                ('team_name', models.CharField(blank=True, help_text='Team name (e.g., U14 Boys)', max_length=100)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite/Competitive')], default='beginner', max_length=20)),
                ('primary_position', models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward'), ('multiple', 'Multiple Positions')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any special needs or notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clients.client')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('sessions_remaining', models.IntegerField()),
                ('sessions_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('exhausted', 'Sessions Exhausted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.package')),
                ('player', models.ForeignKey(blank=True, help_text='Optional: assign package to specific player', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.player')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
