# Generated by Django 4.2.27 on 2025-12-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_amount_paid_booking_client_package_and_more'),
        ('clients', '0002_package_player_clientpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_confirmations', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='email', max_length=10)),
                ('booking_reminders', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='email', max_length=10)),
                ('booking_cancellations', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='email', max_length=10)),
                ('purchase_confirmations', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='email', max_length=10)),
                ('assessment_notifications', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='email', max_length=10)),
                ('promotional_updates', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], default='none', max_length=10)),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Hours before session to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('purchase_confirmed', 'Purchase Confirmed'), ('assessment_ready', 'Assessment Ready'), ('package_expiring', 'Package Expiring Soon'), ('promotional', 'Promotional')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS Text Message'), ('both', 'Email and SMS'), ('none', 'No Notifications')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
