# Generated by Django 4.2.27 on 2025-12-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_remove_playerassessment_effort_rating_and_more'),
        ('clients', '0003_notificationpreference_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.player')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='coaches.scheduleblock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
