# Generated by Django 4.2.27 on 2025-12-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_remove_playerassessment_effort_rating_and_more'),
        ('clients', '0004_sessionreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('parent', 'Parent/Guardian'), ('coach', 'Team Coach')], default='parent', max_length=10),
        ),
        migrations.CreateModel(
            name='BookingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text='List of preferred days')),
                ('preferred_time_slots', models.JSONField(blank=True, default=list, help_text='List of preferred time slots')),
                ('auto_filter', models.BooleanField(default=False, help_text='Automatically filter sessions by preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_preferences', to='clients.client')),
                ('favorite_coaches', models.ManyToManyField(blank=True, related_name='favorited_by', to='coaches.coach')),
            ],
        ),
    ]
