# Generated by Django 4.2.27 on 2025-12-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_client_type_and_booking_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='age_group',
            field=models.CharField(blank=True, help_text='Target age group (e.g., U13, U15)', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='End date for special event', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='event_location',
            field=models.CharField(blank=True, help_text='Location for special event', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='event_start_date',
            field=models.DateField(blank=True, help_text='Start date for special event', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Mark as special event package'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_participants',
            field=models.IntegerField(default=0, help_text='Max participants, 0 for unlimited'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('basic4', 'Basic 4 - 4 classes / 4 weeks'), ('basic8', 'Basic 8 - 8 classes / 4 weeks'), ('elite24', 'Elite 24 - 24 classes / 12 weeks'), ('unlimited', 'Unlimited - 12 weeks'), ('special', 'Special Event Package'), ('team', 'Team Training Package')], max_length=20),
        ),
    ]
