# Generated by Django 4.2.27 on 2025-12-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_create_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('weekly_reminder', 'Weekly Session Reminder'), ('inactive_client', 'Inactive Client Re-engagement'), ('package_expiring', 'Package Expiring Soon'), ('package_exhausted', 'Package Sessions Exhausted'), ('assessment_ready', 'Assessment Ready'), ('upcoming_event', 'Upcoming Event'), ('custom_campaign', 'Custom Campaign'), ('promotional', 'Promotional')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Internal description of this template')),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body_html', models.TextField(help_text='HTML email body. Use {{variable}} for dynamic content.')),
                ('email_body_text', models.TextField(help_text='Plain text email body for non-HTML clients.')),
                ('sms_body', models.CharField(blank=True, help_text='SMS message (160 char limit)', max_length=160)),
                ('target_filters', models.JSONField(blank=True, default=dict, help_text="Filter criteria: {'inactive_weeks': 3, 'has_package': true}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
