# Generated by Django 6.0.3 on 2026-03-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_team'),
        ('clients', '0009_add_push_and_schedule_models'),
    ]

    operations = [
    ]
