# Generated by Django 6.0.3 on 2026-03-12 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_clinic_fields'),
        ('clients', '0010_merge_0002_team_0009_add_push_and_schedule_models'),
        ('coaches', '0004_coach_achievements_coach_coaching_philosophy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRentalSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'Saturday Morning Full Field'", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Owner notes about this slot')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending_approval', 'Pending Approval'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('booker_type', models.CharField(blank=True, choices=[('individual', 'Individual Client'), ('team', 'Team')], max_length=20, null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes submitted with the request')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cancellation_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('purchase_confirmed', 'Purchase Confirmed'), ('assessment_ready', 'Assessment Ready'), ('package_expiring', 'Package Expiring Soon'), ('promotional', 'Promotional'), ('field_rental_request', 'Field Rental Request'), ('field_rental_approved', 'Field Rental Approved'), ('field_rental_rejected', 'Field Rental Rejected'), ('field_rental_cancelled', 'Field Rental Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.CharField(help_text='e.g., U10, U12, U14, U16, U19', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user'], name='clients_cli_user_id_f4ed69_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['client', 'status'], name='clients_cli_client__0593f4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['client', 'expiry_date'], name='clients_cli_client__dc5677_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['status', 'expiry_date'], name='clients_cli_status_8e7fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['client', 'status'], name='clients_not_client__1d41fa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['client', 'notification_type'], name='clients_not_client__e67d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'read_at'], name='clients_not_status_8a34ba_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['booking'], name='clients_not_booking_87eed2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='clients_not_created_f69eda_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'is_special'], name='clients_pac_is_acti_427efd_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['event_start_date', 'event_end_date'], name='clients_pac_event_s_289e21_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['client', 'is_active'], name='clients_pla_client__3b34a0_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['client', 'birth_year'], name='clients_pla_client__981951_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreservation',
            index=models.Index(fields=['client', 'schedule_block'], name='clients_ses_client__dd715a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreservation',
            index=models.Index(fields=['client', 'is_confirmed'], name='clients_ses_client__8e8920_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreservation',
            index=models.Index(fields=['expires_at', 'is_confirmed'], name='clients_ses_expires_b9d6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager', 'is_active'], name='clients_tea_manager_c7d212_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['age_group'], name='clients_tea_age_gro_051ca2_idx'),
        ),
        migrations.AddField(
            model_name='fieldrentalslot',
            name='booked_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_rentals', to='clients.client'),
        ),
        migrations.AddField(
            model_name='fieldrentalslot',
            name='booked_by_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_rentals', to='clients.team'),
        ),
        migrations.AddIndex(
            model_name='fieldrentalslot',
            index=models.Index(fields=['date', 'status'], name='clients_fie_date_0dde72_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldrentalslot',
            index=models.Index(fields=['status', 'date'], name='clients_fie_status_97f78b_idx'),
        ),
    ]
