# Generated by Django 6.0.3 on 2026-03-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_fieldrentalslot_remove_client_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('field_full', 'Full Field'), ('field_partial', 'Partial Field'), ('room', 'Multi-Use Room'), ('gym', 'Gym')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Max people (optional)', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Default price shown to clients', max_digits=8)),
                ('pricing_type', models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Per Hour')], default='flat', max_length=10)),
                ('requires_approval', models.BooleanField(default=True, help_text='Requests need owner approval before confirming')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fieldrentalslot',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service from the catalog (room, gym, partial field, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='clients.rentalservice'),
        ),
    ]
