# Generated by Django 6.0.3 on 2026-03-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_add_rental_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='End time for special event', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='event_start_time',
            field=models.TimeField(blank=True, help_text='Start time for special event', null=True),
        ),
    ]
