# Generated by Django 6.0.3 on 2026-03-30 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_add_player_school_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allowed_services',
            field=models.ManyToManyField(blank=True, help_text='Rental services this client is permitted to book', related_name='allowed_clients', to='clients.rentalservice'),
        ),
        migrations.AddField(
            model_name='client',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Owner notes on approval/rejection'),
        ),
        migrations.AddField(
            model_name='client',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Coaches and renters require owner approval before services are enabled', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='term_end',
            field=models.DateTimeField(blank=True, help_text="When this client's access expires", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='term_start',
            field=models.DateTimeField(blank=True, help_text="When this client's access begins", null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('parent', 'Parent/Guardian'), ('coach', 'Team Coach'), ('renter', 'Facility Renter')], default='parent', max_length=10),
        ),
    ]
