# Generated by Django 6.0.3 on 2026-03-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_add_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (cus_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='clientpackage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID for recurring packages', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for recurring packages (price_xxx)', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientpackage',
            name='stripe_payment_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for one-time purchase', max_length=100),
        ),
    ]
