# Generated by Django 6.0.3 on 2026-04-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_add_stripe_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('basic4', 'Basic 4 - 4 classes / 4 weeks'), ('basic8', 'Basic 8 - 8 classes / 4 weeks'), ('elite24', 'Elite 24 - 24 classes / 12 weeks'), ('unlimited', 'Unlimited - 12 weeks'), ('special', 'Special Event Package'), ('team', 'Team Training Package'), ('select', 'APC Select Membership')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit_type', models.CharField(choices=[('select_monthly', 'APC Select Monthly Credit'), ('manual', 'Manual Grant'), ('referral', 'Referral Credit')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=15)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_to', models.ForeignKey(blank=True, help_text='The ClientPackage this credit was applied against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='clients.clientpackage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_credits', to=settings.AUTH_USER_MODEL)),
                ('source_package', models.ForeignKey(blank=True, help_text='The APC Select ClientPackage that generated this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_credits', to='clients.clientpackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='clients_cli_client__f0572b_idx'), models.Index(fields=['status', 'expires_at'], name='clients_cli_status_99e69c_idx')],
            },
        ),
    ]
