# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations


def create_select_package(apps, schema_editor):
    Package = apps.get_model('clients', 'Package')
    if not Package.objects.filter(package_type='select').exists():
        Package.objects.create(
            name='APC Select Membership',
            package_type='select',
            description=(
                '6-month APC Select membership. Includes: $40/month credit toward APC '
                'Training packages, discounted pick-up sessions ($5), 10% off all camps '
                'and clinics, plus access to monthly team training, outdoor sessions, '
                'and competitive scrimmages. Playing and training kits included.'
            ),
            price='100.00',
            sessions_included=0,    # membership — unlimited access
            validity_weeks=26,      # 6 months
            is_active=True,
            is_special=False,
            max_participants=15,    # 15-player roster per team
        )


def reverse_select_package(apps, schema_editor):
    Package = apps.get_model('clients', 'Package')
    Package.objects.filter(package_type='select', name='APC Select Membership').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_client_credit'),
    ]

    operations = [
        migrations.RunPython(create_select_package, reverse_select_package),
    ]
