# Generated by Django 6.0.3 on 2026-04-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_create_apc_select_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Printed name of signatory', max_length=200)),
                ('signature_text', models.CharField(help_text='Typed signature (full legal name)', max_length=200)),
                ('guardian_name', models.CharField(blank=True, help_text='Parent/guardian name if signing for a minor', max_length=200)),
                ('photo_video_consent', models.BooleanField(default=False, help_text='Consent to photo/video use for promotional purposes')),
                ('waiver_version', models.CharField(default='2026-v1', max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('valid_year', models.IntegerField(help_text='Calendar year this waiver is valid for')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='clients.client')),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['client', 'valid_year'], name='clients_cli_client__2253f5_idx'), models.Index(fields=['waiver_version'], name='clients_cli_waiver__d21c21_idx')],
            },
        ),
    ]
