# Generated by Django 6.0.3 on 2026-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_add_client_waiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('parent', 'Parent/Guardian'), ('athlete', 'Athlete (18+)'), ('coach', 'Team Coach'), ('renter', 'Facility Renter')], default='parent', max_length=10),
        ),
    ]
