# Generated by Django 6.0.3 on 2026-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_self',
            field=models.BooleanField(default=False, help_text='True when this Player record represents the client themselves (Athlete 18+ account type)'),
        ),
    ]
