# Generated by Django 6.0.3 on 2026-04-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_add_player_is_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('sp_camp', 'S&P Camp'), ('apc_summer_2025', 'APC Summer Program 2025'), ('aw_summer_2025', 'AW Summer 2025'), ('ff_camp_jun_2024', 'Future Footballers Camp Jun 2024'), ('ff_camp_jul_2024', 'Future Footballers Camp Jul 2024'), ('ff_program', 'Future Footballers Program'), ('nkc_spring_2025', 'NKC Spring Break 2025'), ('winter_2024', 'Winter Clinic 2024'), ('manual', 'Manually Added'), ('other', 'Other')], default='other', max_length=30)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_import', to='clients.client')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ContactPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, help_text='Raw DOB from source', max_length=30)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Unknown')], max_length=1)),
                ('club_team', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('tshirt_size', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clients.contactparent')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_import', to='clients.player')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='contactparent',
            index=models.Index(fields=['email'], name='clients_con_email_0d7c38_idx'),
        ),
        migrations.AddIndex(
            model_name='contactparent',
            index=models.Index(fields=['client'], name='clients_con_client__95e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactplayer',
            index=models.Index(fields=['parent', 'birth_year'], name='clients_con_parent__167536_idx'),
        ),
    ]
