# Generated by Django 6.0.3 on 2026-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_add_contact_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from new purchases while keeping existing client packages active'),
        ),
    ]
