# Generated by Django 6.0.3 on 2026-04-07 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_add_session_type_allow_package'),
        ('clients', '0023_add_package_is_purchasable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Dollar Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed dollar amount', max_digits=8)),
                ('scope', models.CharField(choices=[('all', 'All Purchases'), ('packages', 'Packages Only'), ('sessions', 'Sessions (Drop-in) Only')], default='all', max_length=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Total redemption limit. Leave blank for unlimited.', null=True)),
                ('max_uses_per_client', models.IntegerField(default=1)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required to use this code', max_digits=8, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL)),
                ('specific_packages', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all packages within scope', related_name='discount_codes', to='clients.package')),
                ('specific_session_types', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all session types within scope', related_name='discount_codes', to='bookings.sessiontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('applied_to_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_uses', to='bookings.booking')),
                ('applied_to_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_uses', to='clients.clientpackage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_uses', to='clients.client')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='clients.discountcode')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
