# Generated by Django 6.0.3 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_add_email_broadcast'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['purchase_date'], name='clients_cli_purchas_af053e_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldrentalslot',
            index=models.Index(fields=['approved_at'], name='clients_fie_approve_8dc43d_idx'),
        ),
    ]
