# Generated by Django 5.2 on 2026-05-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_set_summer_session_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='referralpayout',
            options={'ordering': ['-created_at']},
        ),
        # Index already renamed in prod DB; use SeparateDatabaseAndState so
        # Django's state is updated without attempting the DB rename again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='notificationoutbox',
                    new_name='clients_not_send_af_02e245_idx',
                    old_name='clients_not_send_af_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='clientcredit',
            name='referral',
            field=models.ForeignKey(blank=True, help_text='The Referral that generated this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='clients.referral'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='activation_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of first purchase that triggered activation', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(db_index=True, help_text='Code used for this referral (audit trail)', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_window_expires',
            field=models.DateTimeField(help_text='Referred user must make first purchase by this date (signup + 60 days)'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_type',
            field=models.CharField(choices=[('client', 'Client'), ('coach', 'Coach')], help_text='Determines reward percentage: client=10%, coach=20%', max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated reward (10% or 20% of purchase)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(db_index=True, help_text='8-character uppercase alphanumeric code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Check number, Venmo reference, bank transfer details, etc.'),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        # These 6 indexes already exist in prod DB — update Django state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='referral',
                    index=models.Index(fields=['referrer_user', 'status'], name='clients_ref_referre_db5a97_idx'),
                ),
                migrations.AddIndex(
                    model_name='referral',
                    index=models.Index(fields=['referred_user', 'status'], name='clients_ref_referre_76e133_idx'),
                ),
                migrations.AddIndex(
                    model_name='referral',
                    index=models.Index(fields=['status', 'referral_window_expires'], name='clients_ref_status_d1c640_idx'),
                ),
                migrations.AddIndex(
                    model_name='referralcode',
                    index=models.Index(fields=['code'], name='clients_ref_code_534106_idx'),
                ),
                migrations.AddIndex(
                    model_name='referralpayout',
                    index=models.Index(fields=['coach_user', 'status'], name='clients_ref_coach_u_71fa11_idx'),
                ),
                migrations.AddIndex(
                    model_name='referralpayout',
                    index=models.Index(fields=['status', 'created_at'], name='clients_ref_status_0ae768_idx'),
                ),
            ],
            database_operations=[],
        ),
        # Constraint does not yet exist in prod — apply normally.
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referred_user',), name='one_referral_per_user'),
        ),
    ]
