# Generated by Django 4.2.27 on 2026-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_referral_options_alter_referralpayout_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_opt_out',
            field=models.BooleanField(default=False, help_text='When checked, the client receives no emails at all (one-click unsubscribe).'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
