# Generated by Django 4.2.27 on 2026-07-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_emailsuppression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='billing_tier',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('thirds', 'Every 4 Months (Thirds)'), ('half', 'Every 3 Months (Half)'), ('full', 'Annual (Full Year)')], default='', help_text='Billing interval for Select membership tiers. Leave blank for one-time packages.', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='select_teams',
            field=models.ManyToManyField(blank=True, help_text='Additional Select teams this player is eligible for (guest callups)', limit_choices_to={'is_select': True}, related_name='select_guest_players', to='clients.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_select',
            field=models.BooleanField(default=False, help_text='APC Select team (2014, 2015, 2016, etc.)'),
        ),
    ]
