# Generated by Django 4.2.27 on 2026-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_register_game_day_digest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='select_invited',
            field=models.BooleanField(default=False, help_text='Owner has invited this client to purchase APC Select membership'),
        ),
    ]
