# Generated by Django 4.2.27 on 2026-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_add_select_invited_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='program_group',
            field=models.CharField(blank=True, default='', help_text="Groups packages into a single card with billing picker (e.g. 'Elite 24 Fall')", max_length=100),
        ),
    ]
