# Generated by Django 4.2.27 on 2026-07-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_add_program_group_to_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpackage',
            name='stripe_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID for one-time purchase', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientpackage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID for recurring packages', max_length=100),
        ),
    ]
