# Generated by Django 4.2.27 on 2026-07-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_webhook_idempotency_and_stripe_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientpackage',
            constraint=models.CheckConstraint(check=models.Q(('sessions_remaining__gte', 0)), name='clientpackage_sessions_remaining_non_negative'),
        ),
    ]
