# Generated by Django 5.2 on 2026-08-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_sessions_remaining_check_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcredit',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player this credit is attributed to (set at creation, not inferred from the package)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='clients.player'),
        ),
    ]
