# Generated by Django 5.2 on 2026-08-05 18:10

from django.db import migrations


def backfill_player(apps, schema_editor):
    """Attribute existing select_monthly credits to the player of their source
    package. These rows predate the ClientCredit.player field, so they're all
    NULL by default. Without this backfill, the per-player guard in
    seed_select_credits / _activate_package would find "no credit yet" for
    every existing Select member on their next package save (renewal,
    reassignment, etc.) and grant a duplicate 6-month batch.
    """
    ClientCredit = apps.get_model('clients', 'ClientCredit')
    qs = ClientCredit.objects.filter(
        credit_type='select_monthly',
        player__isnull=True,
        source_package__player__isnull=False,
    ).select_related('source_package')
    for credit in qs:
        credit.player_id = credit.source_package.player_id
        credit.save(update_fields=['player'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_clientcredit_player'),
    ]

    operations = [
        migrations.RunPython(backfill_player, noop_reverse),
    ]
