[pytest]
DJANGO_SETTINGS_MODULE = atletasworld.settings
django_find_project = true
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = src
django_debug_mode = true
addopts = -v --tb=short --strict-markers -rA
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
