# Generated by Django 6.0.3 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_add_performance_indexes'),
        ('clients', '0026_add_performance_indexes'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'status'], name='payments_pa_client__39a683_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
