# Generated by Django 4.2.27 on 2026-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('age_groups', 'Age Groups & Development'), ('programs', 'Programs & Training'), ('select_team', 'Select Team'), ('authority', 'Coach Stories'), ('general', 'General')], default='general', max_length=20)),
                ('excerpt', models.TextField(help_text='1-2 sentences shown in list view', max_length=300)),
                ('body', models.TextField(help_text='HTML content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('og_description', models.CharField(blank=True, help_text='Overrides excerpt for meta description', max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the large featured post at top of list')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
