# Generated by Django 4.2.27 on 2026-08-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0046_sessions_remaining_check_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vald_profile_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vald_tenant_id', models.CharField(db_index=True, max_length=64)),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('manual', 'Manual'), ('auto_name_dob', 'Auto (Name + DOB)'), ('vald_invite', 'VALD Invite')], default='manual', help_text='How this Player was linked to the VALD profile', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vald_profile', to='clients.player')),
            ],
            options={
                'verbose_name': 'VALD Profile',
                'verbose_name_plural': 'VALD Profiles',
            },
        ),
        migrations.CreateModel(
            name='ValdSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, help_text="'profiles' | 'forcedecks' | 'smartspeed' | ...", max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('error', 'Error')], default='running', max_length=10)),
                ('records_synced', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Cursor for incremental pulls (modifiedFromUtc)', null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'VALD Sync Run',
                'verbose_name_plural': 'VALD Sync Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['system', '-started_at'], name='performance_system_1417a5_idx'), models.Index(fields=['status', '-started_at'], name='performance_status_5d02ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValdResultDefinition',
            fields=[
                ('result_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('system', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('trend_direction', models.CharField(blank=True, choices=[('increasing', 'Increasing (higher is better)'), ('decreasing', 'Decreasing (lower is better)'), ('', 'Neutral')], help_text='Polarity for progress charts', max_length=10)),
                ('display_order', models.IntegerField(default=0, help_text='Owner-curated order for client portal charts')),
                ('show_in_client_portal', models.BooleanField(default=False, help_text="Gate this metric's visibility to parents")),
                ('raw_payload', models.JSONField(default=dict)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VALD Result Definition',
                'verbose_name_plural': 'VALD Result Definitions',
                'ordering': ['system', 'display_order', 'name'],
                'indexes': [models.Index(fields=['system', 'show_in_client_portal'], name='performance_system_fb21b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValdTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vald_test_id', models.CharField(db_index=True, help_text='Idempotency key from VALD', max_length=64, unique=True)),
                ('system', models.CharField(choices=[('forcedecks', 'ForceDecks'), ('smartspeed', 'SmartSpeed'), ('dynamo', 'DynaMo'), ('forceframe', 'ForceFrame'), ('humantrak', 'HumanTrak'), ('nordbord', 'NordBord')], db_index=True, max_length=20)),
                ('test_type', models.CharField(help_text="e.g. 'CMJ', 'Sprint_10m'", max_length=80)),
                ('test_date', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField(help_text='Full VALD response for re-derivation')),
                ('metrics', models.JSONField(default=dict, help_text='Flattened {resultId: value} for queryable columns')),
                ('week_key', models.CharField(db_index=True, help_text="ISO week: '2026-W29'", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='performance.valdprofile')),
            ],
            options={
                'verbose_name': 'VALD Test Result',
                'verbose_name_plural': 'VALD Test Results',
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['profile', '-test_date'], name='performance_profile_141b34_idx'), models.Index(fields=['system', 'test_type', '-test_date'], name='performance_system_c5d070_idx'), models.Index(fields=['week_key'], name='performance_week_ke_91d96c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='valdprofile',
            index=models.Index(fields=['vald_tenant_id', 'is_active'], name='performance_vald_te_4287ab_idx'),
        ),
    ]
