# Generated by Django 4.2.27 on 2026-08-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valdresultdefinition',
            name='description',
            field=models.TextField(blank=True, help_text='Parent-friendly explanation of what this metric measures'),
        ),
    ]
