# Generated by Django 4.2.27 on 2025-12-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_notificationpreference_notification'),
        ('bookings', '0002_booking_amount_paid_booking_client_package_and_more'),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('private', 'Private Training (1-on-1)'), ('group', 'Group Training')], default='private', max_length=20)),
                ('duration_minutes', models.IntegerField(choices=[(60, '60 minutes'), (90, '90 minutes')], default=60)),
                ('max_participants', models.IntegerField(default=1, help_text='1 for private, more for group')),
                ('current_participants', models.IntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override default pricing if set', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Fully Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='coaches.coach')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('coach', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('present', 'Present'), ('late', 'Late'), ('absent', 'Absent/No Show')], default='expected', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='bookings.booking')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='coaches.scheduleblock')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('technical', 'Technical Skills'), ('tactical', 'Tactical Awareness'), ('physical', 'Physical Conditioning'), ('dribbling', 'Dribbling'), ('passing', 'Passing'), ('shooting', 'Shooting'), ('defending', 'Defending'), ('goalkeeping', 'Goalkeeping'), ('game_play', 'Game Play/Scrimmage'), ('fitness', 'Fitness Training'), ('mixed', 'Mixed/General Training')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')])),
                ('effort_rating', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], help_text="Player's effort level")),
                ('focus_areas', models.TextField(blank=True, help_text='Areas to focus on for improvement')),
                ('highlights', models.TextField(blank=True, help_text='What the player did well')),
                ('coach_notes', models.TextField(blank=True, help_text='Private notes for coach only')),
                ('parent_visible_notes', models.TextField(blank=True, help_text='Notes visible to parents')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='bookings.booking')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_given', to='coaches.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='clients.player')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
