# Generated by Django 4.2.27 on 2025-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_scheduleblock_sessionattendance_playerassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerassessment',
            name='effort_rating',
        ),
        migrations.RemoveField(
            model_name='playerassessment',
            name='rating',
        ),
        migrations.AddField(
            model_name='playerassessment',
            name='effort_engagement',
            field=models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], default=3, help_text='Effort & Engagement'),
        ),
        migrations.AddField(
            model_name='playerassessment',
            name='goals_achievement',
            field=models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], default=3, help_text='Sessional Goals Achievement'),
        ),
        migrations.AddField(
            model_name='playerassessment',
            name='physical_performance',
            field=models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], default=3, help_text='Physical Performance'),
        ),
        migrations.AddField(
            model_name='playerassessment',
            name='tactical_awareness',
            field=models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], default=3, help_text='Tactical Awareness'),
        ),
        migrations.AddField(
            model_name='playerassessment',
            name='technical_proficiency',
            field=models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Competent'), (4, 'Proficient'), (5, 'Excellent')], default=3, help_text='Technical Proficiency'),
        ),
    ]
