# Generated by Django 4.2.27 on 2025-12-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_remove_playerassessment_effort_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='achievements',
            field=models.TextField(blank=True, help_text='Notable achievements and awards'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_philosophy',
            field=models.TextField(blank=True, help_text='Your coaching philosophy'),
        ),
        migrations.AddField(
            model_name='coach',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Years of coaching experience'),
        ),
        migrations.AddField(
            model_name='coach',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Extended biography for public profile'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/gallery/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/gallery/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/gallery/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile_enabled',
            field=models.BooleanField(default=False, help_text='Enable public profile page (admin must set this)'),
        ),
        migrations.AddField(
            model_name='coach',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly name (e.g., 'mirko' for /coach/mirko/)", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline shown on profile', max_length=200),
        ),
        migrations.AddField(
            model_name='coach',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
