# Generated by Django 6.0.3 on 2026-03-12 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_field_rental_slot_and_more'),
        ('clients', '0011_fieldrentalslot_remove_client_team_and_more'),
        ('coaches', '0004_coach_achievements_coach_coaching_philosophy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['is_active'], name='coaches_coa_is_acti_c92a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['profile_enabled'], name='coaches_coa_profile_fd409e_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['coach', 'player'], name='coaches_pla_coach_i_a510c8_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['coach', 'assessment_date'], name='coaches_pla_coach_i_fddca6_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['player', 'assessment_date'], name='coaches_pla_player__d75834_idx'),
        ),
        migrations.AddIndex(
            model_name='playerassessment',
            index=models.Index(fields=['booking'], name='coaches_pla_booking_548c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['coach', 'date'], name='coaches_sch_coach_i_02c1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['coach', 'status'], name='coaches_sch_coach_i_6f73df_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['date', 'status'], name='coaches_sch_date_f2253d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['status', 'current_participants'], name='coaches_sch_status_0318ea_idx'),
        ),
    ]
