# Generated by Django 6.0.3 on 2026-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_start_times'),
        ('coaches', '0005_coach_coaches_coa_is_acti_c92a6d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='catalog_session_types',
            field=models.ManyToManyField(blank=True, help_text='Session types offered in this block', related_name='schedule_blocks', to='bookings.sessiontype'),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='session_type',
            field=models.CharField(choices=[('private', 'Private Training (1-on-1)'), ('group', 'Group Training')], default='group', max_length=20),
        ),
    ]
