# Generated by Django 6.0.3 on 2026-04-06 16:43

from django.db import migrations
import datetime

TRYOUT_BLOCKS = [
    # May 21 — APC indoor, age-specific
    {'date': datetime.date(2026, 5, 21), 'start': datetime.time(18, 0), 'end': datetime.time(19, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2016s'},
    {'date': datetime.date(2026, 5, 21), 'start': datetime.time(19, 0), 'end': datetime.time(20, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2015s'},
    {'date': datetime.date(2026, 5, 21), 'start': datetime.time(20, 0), 'end': datetime.time(21, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2014s'},
    # May 22 — APC indoor, age-specific
    {'date': datetime.date(2026, 5, 22), 'start': datetime.time(18, 0), 'end': datetime.time(19, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2016s'},
    {'date': datetime.date(2026, 5, 22), 'start': datetime.time(19, 0), 'end': datetime.time(20, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2015s'},
    {'date': datetime.date(2026, 5, 22), 'start': datetime.time(20, 0), 'end': datetime.time(21, 0), 'dur': 60,  'max': 30, 'session_name': 'APC Select Tryout — 2014s'},
    # May 23 — Hocker Grove outdoor, all ages
    {'date': datetime.date(2026, 5, 23), 'start': datetime.time(9, 0),  'end': datetime.time(11, 0), 'dur': 120, 'max': 60, 'session_name': 'APC Select Tryout — All Ages'},
    # May 24 — Hocker Grove outdoor, all ages
    {'date': datetime.date(2026, 5, 24), 'start': datetime.time(9, 0),  'end': datetime.time(11, 0), 'dur': 120, 'max': 60, 'session_name': 'APC Select Tryout — All Ages'},
]


def create_blocks(apps, schema_editor):
    Coach = apps.get_model('coaches', 'Coach')
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType = apps.get_model('bookings', 'SessionType')

    # Use head coach (mirko) — fall back to first active coach
    coach = (
        Coach.objects.filter(user__email__icontains='mirko').first()
        or Coach.objects.filter(is_active=True).first()
    )
    if not coach:
        return  # no coaches yet — owner will create blocks manually

    for b in TRYOUT_BLOCKS:
        st = SessionType.objects.filter(name=b['session_name']).first()
        if not st:
            continue
        # Skip if block already exists for this date/time/coach
        if ScheduleBlock.objects.filter(coach=coach, date=b['date'], start_time=b['start']).exists():
            continue
        block = ScheduleBlock.objects.create(
            coach=coach,
            session_type='group',
            date=b['date'],
            start_time=b['start'],
            end_time=b['end'],
            duration_minutes=b['dur'],
            max_participants=b['max'],
            status='available',
            current_participants=0,
        )
        block.catalog_session_types.set([st])


def reverse_blocks(apps, schema_editor):
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    for b in TRYOUT_BLOCKS:
        ScheduleBlock.objects.filter(date=b['date'], start_time=b['start']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_add_catalog_session_types_m2m'),
        ('bookings', '0012_add_apc_select_tryout_session_types'),
    ]

    operations = [
        migrations.RunPython(create_blocks, reverse_blocks),
    ]
