# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations
import datetime

# Every Sunday Apr 12 – Dec 27 2026
def _sundays():
    d = datetime.date(2026, 4, 12)
    end = datetime.date(2026, 12, 27)
    while d <= end:
        yield d
        d += datetime.timedelta(weeks=1)

SERIE_A_SLOTS = [
    # (session_type_name, start_time, end_time, duration_minutes, max_participants)
    ('Serie A Elite Scouts — U13', datetime.time(16, 0),  datetime.time(17, 30), 90, 20),
    ('Serie A Elite Scouts — U19', datetime.time(17, 30), datetime.time(19, 0),  90, 20),
]


def create_blocks(apps, schema_editor):
    Coach = apps.get_model('coaches', 'Coach')
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType = apps.get_model('bookings', 'SessionType')

    coach = (
        Coach.objects.filter(user__email__icontains='mirko').first()
        or Coach.objects.filter(is_active=True).first()
    )
    if not coach:
        return

    sundays = list(_sundays())

    for st_name, start, end, dur, max_p in SERIE_A_SLOTS:
        st = SessionType.objects.filter(name=st_name).first()
        if not st:
            continue
        for date in sundays:
            if ScheduleBlock.objects.filter(coach=coach, date=date, start_time=start).exists():
                continue
            block = ScheduleBlock.objects.create(
                coach=coach,
                session_type='group',
                date=date,
                start_time=start,
                end_time=end,
                duration_minutes=dur,
                max_participants=max_p,
                status='available',
                current_participants=0,
            )
            block.catalog_session_types.set([st])


def reverse_blocks(apps, schema_editor):
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    for st_name, start, end, dur, max_p in SERIE_A_SLOTS:
        ScheduleBlock.objects.filter(start_time=start, date__week_day=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_create_tryout_schedule_blocks'),
        ('bookings', '0013_add_serie_a_session_types'),
    ]

    operations = [
        migrations.RunPython(create_blocks, reverse_blocks),
    ]
