# Generated by Django 6.0.3 on 2026-04-07
# Pick-Up Game blocks Mon/Wed/Fri/Sat 12-2pm, May 18 – Aug 8 2026, Mirko, 20/slot

import datetime
from django.db import migrations


def _slots():
    TARGET = {0, 2, 4, 5}  # Mon=0, Wed=2, Fri=4, Sat=5
    d, end = datetime.date(2026, 5, 18), datetime.date(2026, 8, 8)
    while d <= end:
        if d.weekday() in TARGET:
            yield d
        d += datetime.timedelta(days=1)


def create_blocks(apps, schema_editor):
    Coach         = apps.get_model('coaches', 'Coach')
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType   = apps.get_model('bookings', 'SessionType')

    coach = (
        Coach.objects.filter(user__email__icontains='mirko').first()
        or Coach.objects.filter(user__username='mirko').first()
        or Coach.objects.filter(is_active=True).first()
    )
    if not coach:
        return

    st = SessionType.objects.filter(name='Pick-Up Game').first()
    start_t, end_t = datetime.time(12, 0), datetime.time(14, 0)

    for date in _slots():
        if ScheduleBlock.objects.filter(coach=coach, date=date, start_time=start_t).exists():
            continue
        block = ScheduleBlock.objects.create(
            coach=coach,
            session_type='group',
            date=date,
            start_time=start_t,
            end_time=end_t,
            duration_minutes=120,
            max_participants=20,
            status='available',
            current_participants=0,
        )
        if st:
            block.catalog_session_types.set([st])


def reverse_blocks(apps, schema_editor):
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    ScheduleBlock.objects.filter(
        date__range=(datetime.date(2026, 5, 18), datetime.date(2026, 8, 8)),
        start_time=datetime.time(12, 0),
        end_time=datetime.time(14, 0),
        max_participants=20,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0008_add_serie_a_schedule_blocks'),
        ('bookings', '0016_add_session_type_allow_package'),
    ]

    operations = [
        migrations.RunPython(create_blocks, reverse_blocks),
    ]
