# Generated by Django 6.0.3 on 2026-04-07
# Summer Program schedule blocks — Tue/Thu, May 19–Aug 6 2026
# HS/College:     7AM-8:30AM, 10:30AM-12PM, 6PM-7:30PM
# U13 & Younger:  9AM-10:30AM, 4:30PM-6PM, 6PM-7:30PM
# Coach: Mirko · 30 max/slot

import datetime
from django.db import migrations

# (session_type_names_list, start, end)
# 6PM shared — one block linked to both session types
ALL_SLOTS = [
    (['Summer Program HS/College'],              datetime.time(7,  0), datetime.time(8, 30)),
    (['Summer Program U13 & Younger'],           datetime.time(9,  0), datetime.time(10,30)),
    (['Summer Program HS/College'],              datetime.time(10,30), datetime.time(12, 0)),
    (['Summer Program U13 & Younger'],           datetime.time(16,30), datetime.time(18, 0)),
    # 6PM: single block for both groups (unique constraint on coach+date+start_time)
    (['Summer Program HS/College',
      'Summer Program U13 & Younger'],           datetime.time(18, 0), datetime.time(19,30)),
]


def _tue_thu(start, end):
    """Yield every Tuesday (1) and Thursday (3) between start and end inclusive."""
    d = start
    while d <= end:
        if d.weekday() in (1, 3):
            yield d
        d += datetime.timedelta(days=1)


def create_blocks(apps, schema_editor):
    Coach         = apps.get_model('coaches', 'Coach')
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType   = apps.get_model('bookings', 'SessionType')

    coach = (
        Coach.objects.filter(user__email__icontains='mirko').first()
        or Coach.objects.filter(user__username='mirko').first()
        or Coach.objects.filter(is_active=True).first()
    )
    if not coach:
        return

    # Cache session types by name
    st_map = {}
    for names, _, _ in ALL_SLOTS:
        for name in names:
            if name not in st_map:
                st_map[name] = SessionType.objects.filter(name=name).first()

    start_date = datetime.date(2026, 5, 18)
    end_date   = datetime.date(2026, 8, 8)

    for date in _tue_thu(start_date, end_date):
        for st_names, s_time, e_time in ALL_SLOTS:
            if ScheduleBlock.objects.filter(
                coach=coach, date=date, start_time=s_time,
            ).exists():
                continue
            block = ScheduleBlock.objects.create(
                coach=coach,
                session_type='group',
                date=date,
                start_time=s_time,
                end_time=e_time,
                duration_minutes=90,
                max_participants=10,
                status='available',
                current_participants=0,
            )
            sts = [st_map[n] for n in st_names if st_map.get(n)]
            if sts:
                block.catalog_session_types.set(sts)


def reverse_blocks(apps, schema_editor):
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    # Remove only the exact blocks created above (Tue/Thu, specific times, 90min, 30 max)
    for date in _tue_thu(datetime.date(2026, 5, 18), datetime.date(2026, 8, 8)):
        for _, s_time, e_time in ALL_SLOTS:
            ScheduleBlock.objects.filter(
                date=date, start_time=s_time, end_time=e_time,
                duration_minutes=90, max_participants=30,
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_create_pickup_schedule_blocks'),
        ('bookings', '0016_add_session_type_allow_package'),
    ]

    operations = [
        migrations.RunPython(create_blocks, reverse_blocks),
    ]
