# Generated by Django 6.0.3 on 2026-04-07
# Summer Program 2026 — location_override field + indoor schedule blocks
#
# Part A: Adds location_override to ScheduleBlock, backfills Tue/Thu outdoor blocks:
#   morning  (07:00, 09:00, 10:30) → Hocker Grove Middle School
#   evening  (16:30, 18:00)        → Shawnee Mission North HS Practice Field
#   Also sets SessionType.location = "APC Indoor Facility" on both Summer Program types.
#
# Part B: Creates Mon/Wed/Fri + Sat/Sun APC Indoor blocks (May 18–Aug 8 2026):
#   Mon/Wed/Fri — 5 slots per day (same time pattern as Tue/Thu outdoor)
#   Sat/Sun     — 2 shared slots per day (9AM and 10:30AM)

import datetime
from django.db import migrations, models


MORNING_TIMES = {datetime.time(7, 0), datetime.time(9, 0), datetime.time(10, 30)}
EVENING_TIMES = {datetime.time(16, 30), datetime.time(18, 0)}

HOCKER_GROVE     = "Hocker Grove Middle School"
SHAWNEE_MISSION  = "Shawnee Mission North HS Practice Field"
APC_INDOOR       = "APC Indoor Facility"

MWF_SLOTS = [
    (['Summer Program HS/College'],                         datetime.time(7,  0), datetime.time(8, 30)),
    (['Summer Program U13 & Younger'],                      datetime.time(9,  0), datetime.time(10, 30)),
    (['Summer Program HS/College'],                         datetime.time(10, 30), datetime.time(12, 0)),
    (['Summer Program U13 & Younger'],                      datetime.time(16, 30), datetime.time(18, 0)),
    (['Summer Program HS/College', 'Summer Program U13 & Younger'], datetime.time(18, 0), datetime.time(19, 30)),
]

WEEKEND_SLOTS = [
    (['Summer Program HS/College', 'Summer Program U13 & Younger'], datetime.time(9,  0), datetime.time(10, 30)),
    (['Summer Program HS/College', 'Summer Program U13 & Younger'], datetime.time(10, 30), datetime.time(12, 0)),
]


def _days_between(start, end, weekdays):
    """Yield every date between start and end (inclusive) whose weekday() is in weekdays."""
    d = start
    while d <= end:
        if d.weekday() in weekdays:
            yield d
        d += datetime.timedelta(days=1)


def apply_locations_and_create_indoor(apps, schema_editor):
    Coach         = apps.get_model('coaches', 'Coach')
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType   = apps.get_model('bookings', 'SessionType')

    # --- Part A: backfill outdoor Tue/Thu blocks ---
    for block in ScheduleBlock.objects.filter(date__range=(datetime.date(2026, 5, 18), datetime.date(2026, 8, 8))):
        if block.date.weekday() in (1, 3):  # Tue, Thu
            if block.start_time in MORNING_TIMES:
                block.location_override = HOCKER_GROVE
                block.save(update_fields=['location_override'])
            elif block.start_time in EVENING_TIMES:
                block.location_override = SHAWNEE_MISSION
                block.save(update_fields=['location_override'])

    # --- Part A: set default location on both Summer Program session types ---
    for name in ('Summer Program HS/College', 'Summer Program U13 & Younger'):
        st = SessionType.objects.filter(name=name).first()
        if st and not st.location:
            st.location = APC_INDOOR
            st.save(update_fields=['location'])

    # --- Part B: create indoor blocks ---
    coach = (
        Coach.objects.filter(user__email__icontains='mirko').first()
        or Coach.objects.filter(user__username='mirko').first()
        or Coach.objects.filter(is_active=True).first()
    )
    if not coach:
        return

    st_map = {}
    for names, _, _ in MWF_SLOTS + WEEKEND_SLOTS:
        for name in names:
            if name not in st_map:
                st_map[name] = SessionType.objects.filter(name=name).first()

    start_date = datetime.date(2026, 5, 18)
    end_date   = datetime.date(2026, 8, 8)

    # Mon=0, Wed=2, Fri=4
    for date in _days_between(start_date, end_date, (0, 2, 4)):
        for st_names, s_time, e_time in MWF_SLOTS:
            if ScheduleBlock.objects.filter(coach=coach, date=date, start_time=s_time).exists():
                continue
            block = ScheduleBlock.objects.create(
                coach=coach,
                session_type='group',
                date=date,
                start_time=s_time,
                end_time=e_time,
                duration_minutes=90,
                max_participants=10,
                status='available',
                current_participants=0,
            )
            sts = [st_map[n] for n in st_names if st_map.get(n)]
            if sts:
                block.catalog_session_types.set(sts)

    # Sat=5, Sun=6
    for date in _days_between(start_date, end_date, (5, 6)):
        for st_names, s_time, e_time in WEEKEND_SLOTS:
            if ScheduleBlock.objects.filter(coach=coach, date=date, start_time=s_time).exists():
                continue
            block = ScheduleBlock.objects.create(
                coach=coach,
                session_type='group',
                date=date,
                start_time=s_time,
                end_time=e_time,
                duration_minutes=90,
                max_participants=10,
                status='available',
                current_participants=0,
            )
            sts = [st_map[n] for n in st_names if st_map.get(n)]
            if sts:
                block.catalog_session_types.set(sts)


def reverse_locations_and_indoor(apps, schema_editor):
    ScheduleBlock = apps.get_model('coaches', 'ScheduleBlock')
    SessionType   = apps.get_model('bookings', 'SessionType')

    # Clear outdoor location overrides
    ScheduleBlock.objects.filter(
        date__range=(datetime.date(2026, 5, 18), datetime.date(2026, 8, 8)),
        location_override__in=[HOCKER_GROVE, SHAWNEE_MISSION],
    ).update(location_override='')

    # Clear session type locations set by this migration
    for name in ('Summer Program HS/College', 'Summer Program U13 & Younger'):
        st = SessionType.objects.filter(name=name, location=APC_INDOOR).first()
        if st:
            st.location = ''
            st.save(update_fields=['location'])

    # Remove indoor blocks created by this migration (Mon/Wed/Fri/Sat/Sun, 90min, 10 max)
    start_date = datetime.date(2026, 5, 18)
    end_date   = datetime.date(2026, 8, 8)
    for date in _days_between(start_date, end_date, (0, 2, 4, 5, 6)):
        for _, s_time, e_time in MWF_SLOTS + WEEKEND_SLOTS:
            ScheduleBlock.objects.filter(
                date=date, start_time=s_time, end_time=e_time,
                duration_minutes=90, max_participants=10,
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0010_create_summer_program_schedule_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='location_override',
            field=models.CharField(
                blank=True,
                help_text='Overrides session type location for this block (e.g. outdoor venue)',
                max_length=200,
            ),
        ),
        migrations.RunPython(apply_locations_and_create_indoor, reverse_locations_and_indoor),
    ]
