# Generated by Django 6.0.3 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_add_performance_indexes'),
        ('coaches', '0011_scheduleblock_location_override_and_indoor_blocks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['date', 'start_time'], name='coaches_sch_date_808e80_idx'),
        ),
    ]
