# Generated by Django 4.2.27 on 2026-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='sessions_display_floor',
            field=models.IntegerField(default=0, help_text='Minimum session count shown publicly (accounts for pre-platform history)'),
        ),
    ]
