# Generated by Django 4.2.27 on 2026-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0015_copy_static_photos_to_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['display_order', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='coach',
            name='display_order',
            field=models.IntegerField(default=10, help_text='Sort order on public pages — lower = first (Roger=1, Mirko=2, etc.)'),
        ),
    ]
