# Generated by Django 4.2.27 on 2026-07-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_select_team_flag_and_player_select_teams_and_billing_tier'),
        ('coaches', '0016_add_display_order_to_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='select_team',
            field=models.ForeignKey(blank=True, help_text='Restrict this block to a specific Select team. Leave blank for all-Select or non-Select sessions.', limit_choices_to={'is_select': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_blocks', to='clients.team'),
        ),
    ]
