# Generated by Django 5.2 on 2026-08-07 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_backfill_clientcredit_player'),
        ('coaches', '0017_add_select_team_to_schedule_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('bleep_test', 'Bleep Test')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, help_text='Numeric result, e.g. distance in meters', max_digits=8)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('test_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_test_results_entered', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_test_results', to='clients.player')),
            ],
            options={
                'ordering': ['-test_date', '-created_at'],
                'indexes': [models.Index(fields=['player', 'test_type'], name='coaches_man_player__6d59e9_idx'), models.Index(fields=['test_type', 'test_date'], name='coaches_man_test_ty_76ae32_idx')],
            },
        ),
    ]
