# Generated by Django 5.2 on 2026-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0018_manualtestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtestresult',
            name='unit',
            field=models.CharField(choices=[('meters', 'Meters (m)'), ('feet', 'Feet (ft)'), ('seconds', 'Time (sec)')], default='meters', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualtestresult',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Numeric result, e.g. distance or time', max_digits=8),
        ),
    ]
