# Generated by Django 4.2.27 on 2025-12-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_package_player_clientpackage'),
        ('coaches', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_package',
            field=models.ForeignKey(blank=True, help_text='Package used for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.clientpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('package', 'Package'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(blank=True, help_text='The player attending the session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.player'),
        ),
        migrations.AddField(
            model_name='program',
            name='max_age',
            field=models.IntegerField(blank=True, help_text='Maximum age for this program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='Minimum age for this program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('drop_in', 'Drop-in (Pay per session)'), ('package', 'Package Required'), ('event', 'Special Event')], default='drop_in', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='requires_package',
            field=models.BooleanField(default=False, help_text='Requires active package to book'),
        ),
        migrations.AddField(
            model_name='program',
            name='skill_levels',
            field=models.CharField(blank=True, help_text='Comma-separated skill levels: beginner,intermediate,advanced,elite', max_length=100),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('spots_total', models.IntegerField(default=20)),
                ('spots_remaining', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coaches.coach')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bookings.program')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('program', 'coach', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.session'),
        ),
    ]
