# Generated by Django 4.2.27 on 2025-12-09 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaches', '0003_remove_playerassessment_effort_rating_and_more'),
        ('bookings', '0002_booking_amount_paid_booking_client_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('session_format', models.CharField(choices=[('private', 'Private (1-on-1)'), ('semi_private', 'Semi-Private (2-3 players)'), ('group', 'Group Session'), ('clinic', 'Clinic/Camp')], default='private', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_participants', models.IntegerField(default=1)),
                ('color', models.CharField(default='#2ecc71', help_text='Hex color for calendar display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_package', models.BooleanField(default=False, help_text='Requires active package to book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='program',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session',
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_request', 'Client Request'), ('coach_unavailable', 'Coach Unavailable'), ('weather', 'Weather'), ('illness', 'Illness'), ('emergency', 'Emergency'), ('rescheduled', 'Rescheduled to Another Time'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Notes from client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coach_notes',
            field=models.TextField(blank=True, help_text='Private notes from coach'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('package', 'Package Used'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='requires_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='skill_levels',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='End date for recurring slots', null=True)),
                ('max_bookings', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('partially_booked', 'Partially Booked'), ('fully_booked', 'Fully Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override session type price if set', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='coaches.coach')),
                ('parent_slot', models.ForeignKey(blank=True, help_text='Parent slot for recurring series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='bookings.availabilityslot')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='bookings.sessiontype')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('coach', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.availabilityslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.sessiontype'),
        ),
        migrations.AddField(
            model_name='program',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_programs', to='bookings.sessiontype'),
        ),
    ]
