# Generated by Django 4.2.27 on 2025-12-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for clinics/camps', null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='location',
            field=models.CharField(blank=True, help_text='Location for clinics/camps', max_length=200),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='max_age',
            field=models.IntegerField(blank=True, help_text='Maximum age restriction', null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='Minimum age restriction', null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for clinics/camps', null=True),
        ),
    ]
