# Generated by Django 6.0.3 on 2026-03-12 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_clinic_fields'),
        ('clients', '0011_fieldrentalslot_remove_client_team_and_more'),
        ('coaches', '0004_coach_achievements_coach_coaching_philosophy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='field_rental_slot',
            field=models.ForeignKey(blank=True, help_text='Set if this booking is for a full field rental', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_record', to='clients.fieldrentalslot'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['coach', 'date'], name='bookings_av_coach_i_9c595d_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['coach', 'status'], name='bookings_av_coach_i_313989_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['date', 'status'], name='bookings_av_date_653f86_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['status', 'recurrence'], name='bookings_av_status_af6644_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'scheduled_date'], name='bookings_bo_client__a3597b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_bo_client__09b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['coach', 'scheduled_date'], name='bookings_bo_coach_i_378ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['coach', 'status'], name='bookings_bo_coach_i_6c896b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_date', 'status'], name='bookings_bo_schedul_75f830_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', 'status'], name='bookings_bo_player__998c55_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_package'], name='bookings_bo_client__51ccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_status'], name='bookings_bo_status_92d418_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontype',
            index=models.Index(fields=['is_active', 'session_format'], name='bookings_se_is_acti_932205_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontype',
            index=models.Index(fields=['requires_package'], name='bookings_se_require_9f82be_idx'),
        ),
    ]
