# Generated by Django 6.0.3 on 2026-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_field_rental_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='show_as_event',
            field=models.BooleanField(default=False, help_text='Show in Upcoming Events on homepage'),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='show_as_program',
            field=models.BooleanField(default=False, help_text='Show in Training Programs on homepage'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='session_format',
            field=models.CharField(choices=[('private', 'Private (1-on-1)'), ('semi_private', 'Semi-Private (2-3 players)'), ('group', 'Group Session'), ('team', 'Team Training'), ('clinic', 'Clinic'), ('camp', 'Camp'), ('seasonal', 'Seasonal (Package Pre-paid)'), ('pickup', 'Pick Up Game')], default='private', max_length=20),
        ),
    ]
