# Generated by Django 6.0.3 on 2026-03-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_homepage_display_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='age_group',
            field=models.CharField(blank=True, help_text='Target age group (e.g., U13-U15, All ages)', max_length=100),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Comma-separated days, e.g. Mon,Wed,Fri', max_length=50),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='location',
            field=models.CharField(blank=True, help_text='Training location', max_length=200),
        ),
    ]
