# Generated by Django 6.0.3 on 2026-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_add_location_agegroup_days'),
        ('clients', '0013_add_event_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='linked_packages',
            field=models.ManyToManyField(blank=True, help_text='Packages that include access to this seasonal session', related_name='session_types', to='clients.package'),
        ),
    ]
