# Generated by Django 6.0.3 on 2026-03-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_linked_packages_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='start_times',
            field=models.CharField(blank=True, help_text='Comma-separated start times, e.g. 09:00,10:30,14:00', max_length=200),
        ),
    ]
