# Generated by Django 6.0.3 on 2026-03-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_start_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='drop_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Drop-in fee for clients without a package. Leave blank to use standard price.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Package/standard price per session', max_digits=8),
        ),
    ]
