# Generated by Django 6.0.3 on 2026-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_drop_in_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='weekend_start_times',
            field=models.CharField(blank=True, help_text='Weekend (Sat–Sun) start times. Leave blank to use weekday times.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='start_times',
            field=models.CharField(blank=True, help_text='Weekday (Mon–Fri) start times, space-separated e.g. 09:00 10:30 16:30', max_length=200),
        ),
    ]
