# Generated by Django 6.0.3 on 2026-04-06 16:19

from django.db import migrations
import datetime


TRYOUT_SESSION_TYPES = [
    {
        'name': 'APC Select Tryout — 2016s',
        'description': (
            'APC Select tryout for 2016 birth year (boys). '
            'Tryout sessions: May 21 @ 6PM and May 22 @ 6PM at APC; '
            'May 23–24 @ 9AM–11AM at Hocker Grove Middle School.'
        ),
        'session_format': 'tryout',
        'duration_minutes': 60,
        'price': '0.00',
        'drop_in_price': '0.00',
        'max_participants': 30,
        'color': '#6366f1',
        'is_active': True,
        'requires_package': False,
        'show_as_event': True,
        'show_as_program': False,
        'location': 'Atletas Performance Center / Hocker Grove Middle School',
        'age_group': '2016 (Born 2016)',
        'days_of_week': 'Wed,Thu,Fri,Sat',
        'start_times': '18:00',
        'weekend_start_times': '09:00',
        'start_date': datetime.date(2026, 5, 21),
        'end_date': datetime.date(2026, 5, 24),
    },
    {
        'name': 'APC Select Tryout — 2015s',
        'description': (
            'APC Select tryout for 2015 birth year (boys). '
            'Tryout sessions: May 21 @ 7PM and May 22 @ 7PM at APC; '
            'May 23–24 @ 9AM–11AM at Hocker Grove Middle School.'
        ),
        'session_format': 'tryout',
        'duration_minutes': 60,
        'price': '0.00',
        'drop_in_price': '0.00',
        'max_participants': 30,
        'color': '#8b5cf6',
        'is_active': True,
        'requires_package': False,
        'show_as_event': True,
        'show_as_program': False,
        'location': 'Atletas Performance Center / Hocker Grove Middle School',
        'age_group': '2015 (Born 2015)',
        'days_of_week': 'Wed,Thu,Fri,Sat',
        'start_times': '19:00',
        'weekend_start_times': '09:00',
        'start_date': datetime.date(2026, 5, 21),
        'end_date': datetime.date(2026, 5, 24),
    },
    {
        'name': 'APC Select Tryout — 2014s',
        'description': (
            'APC Select tryout for 2014 birth year (boys). '
            'Tryout sessions: May 21 @ 8PM and May 22 @ 8PM at APC; '
            'May 23–24 @ 9AM–11AM at Hocker Grove Middle School.'
        ),
        'session_format': 'tryout',
        'duration_minutes': 60,
        'price': '0.00',
        'drop_in_price': '0.00',
        'max_participants': 30,
        'color': '#a78bfa',
        'is_active': True,
        'requires_package': False,
        'show_as_event': True,
        'show_as_program': False,
        'location': 'Atletas Performance Center / Hocker Grove Middle School',
        'age_group': '2014 (Born 2014)',
        'days_of_week': 'Wed,Thu,Fri,Sat',
        'start_times': '20:00',
        'weekend_start_times': '09:00',
        'start_date': datetime.date(2026, 5, 21),
        'end_date': datetime.date(2026, 5, 24),
    },
    {
        'name': 'APC Select Tryout — All Ages',
        'description': (
            'APC Select open tryout for all ages (2014, 2015, 2016 boys; girls 2017/2018; '
            '2013 players entering 7th grade). '
            'May 23–24 @ 9AM–11AM at Hocker Grove Middle School.'
        ),
        'session_format': 'tryout',
        'duration_minutes': 120,
        'price': '0.00',
        'drop_in_price': '0.00',
        'max_participants': 60,
        'color': '#d97706',
        'is_active': True,
        'requires_package': False,
        'show_as_event': True,
        'show_as_program': False,
        'location': 'Hocker Grove Middle School',
        'age_group': 'All ages (2013–2018)',
        'days_of_week': 'Fri,Sat',
        'start_times': '09:00',
        'weekend_start_times': '09:00',
        'start_date': datetime.date(2026, 5, 23),
        'end_date': datetime.date(2026, 5, 24),
    },
]


def create_tryout_session_types(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for data in TRYOUT_SESSION_TYPES:
        if not SessionType.objects.filter(name=data['name']).exists():
            SessionType.objects.create(**data)


def reverse_tryout_session_types(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for data in TRYOUT_SESSION_TYPES:
        SessionType.objects.filter(name=data['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_add_weekend_start_times'),
    ]

    operations = [
        migrations.RunPython(
            create_tryout_session_types,
            reverse_tryout_session_types,
        ),
    ]
