# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations

SERIE_A_TYPES = [
    {
        'name': 'Serie A Elite Scouts — U13',
        'description': (
            'High-performance elite development class for U13 players (born 2014–2018). '
            'Every Sunday, 90-minute session coached at a Serie A scouting standard. '
            '20-player cap. $40 per session.'
        ),
        'session_format': 'group',
        'duration_minutes': 90,
        'price': '40.00',
        'drop_in_price': '40.00',
        'max_participants': 20,
        'color': '#16a34a',   # green
        'is_active': True,
        'requires_package': False,
        'show_as_event': False,
        'show_as_program': True,
        'location': 'Atletas Performance Center',
        'age_group': 'U13 (Born 2014–2018)',
        'days_of_week': 'Sun',
        'start_times': '16:00',
        'weekend_start_times': '16:00',
        'min_age': None,
        'max_age': None,
    },
    {
        'name': 'Serie A Elite Scouts — U19',
        'description': (
            'High-performance elite development class for U19 players (born 2007–2013). '
            'Every Sunday, 90-minute session coached at a Serie A scouting standard. '
            '20-player cap. $40 per session.'
        ),
        'session_format': 'group',
        'duration_minutes': 90,
        'price': '40.00',
        'drop_in_price': '40.00',
        'max_participants': 20,
        'color': '#0284c7',   # blue
        'is_active': True,
        'requires_package': False,
        'show_as_event': False,
        'show_as_program': True,
        'location': 'Atletas Performance Center',
        'age_group': 'U19 (Born 2007–2013)',
        'days_of_week': 'Sun',
        'start_times': '17:30',
        'weekend_start_times': '17:30',
        'min_age': None,
        'max_age': None,
    },
]


def create_session_types(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for data in SERIE_A_TYPES:
        if not SessionType.objects.filter(name=data['name']).exists():
            SessionType.objects.create(**data)


def reverse_session_types(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for data in SERIE_A_TYPES:
        SessionType.objects.filter(name=data['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_add_apc_select_tryout_session_types'),
    ]

    operations = [
        migrations.RunPython(create_session_types, reverse_session_types),
    ]
