# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations

RENAMES = [
    ('APC Select Tryout — 2014s', 'Tryout 2014'),
    ('APC Select Tryout — 2015s', 'Tryout 2015'),
    ('APC Select Tryout — 2016s', 'Tryout 2016'),
    ('APC Select Tryout — All Ages', 'Tryout All Ages'),
]


def rename_forward(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for old, new in RENAMES:
        SessionType.objects.filter(name=old).update(name=new)


def rename_reverse(apps, schema_editor):
    SessionType = apps.get_model('bookings', 'SessionType')
    for old, new in RENAMES:
        SessionType.objects.filter(name=new).update(name=old)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_add_serie_a_session_types'),
    ]

    operations = [
        migrations.RunPython(rename_forward, rename_reverse),
    ]
