# Generated by Django 6.0.3 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_sessiontype_session_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='allow_package',
            field=models.BooleanField(default=True, help_text='Allow package sessions to be used for this session type. Uncheck for drop-in only sessions (e.g. Private Training) where each booking is always charged individually.'),
        ),
    ]
