# Generated by Django 6.0.3 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_add_session_type_allow_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='session_format',
            field=models.CharField(choices=[('private', 'Private (1-on-1)'), ('semi_private', 'Semi-Private (2-3 players)'), ('group', 'Group Session'), ('team', 'Team Training'), ('clinic', 'Clinic'), ('camp', 'Camp'), ('seasonal', 'Seasonal Package'), ('pickup', 'Pick Up Game'), ('tryout', 'Tryout')], default='private', max_length=20),
        ),
    ]
