# Generated by Django 6.0.3 on 2026-04-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_add_day_capacities'),
        ('bookings', '0018_sessiontype_event_carousel'),
    ]

    operations = [
    ]
