# Generated by Django 6.0.3 on 2026-04-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_add_tournament_format_and_fifa_event'),
        ('bookings', '0020_fix_event_cta_urls'),
    ]

    operations = [
    ]
