# Generated by Django 4.2.27 on 2026-07-21 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0017_add_select_team_to_schedule_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0040_select_team_flag_and_player_select_teams_and_billing_tier'),
        ('bookings', '0021_merge_20260418_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Opponent, field number, instructions, etc.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_games', to='coaches.coach')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_select_games', to=settings.AUTH_USER_MODEL)),
                ('guest_invitees', models.ManyToManyField(blank=True, help_text='Non-Select clients manually invited by owner/coach', related_name='game_invites', to='clients.client')),
                ('team', models.ForeignKey(limit_choices_to={'is_select': True}, on_delete=django.db.models.deletion.CASCADE, related_name='select_games', to='clients.team')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='session_format',
            field=models.CharField(choices=[('private', 'Private (1-on-1)'), ('semi_private', 'Semi-Private (2-3 players)'), ('group', 'Group Session'), ('team', 'Team Training'), ('clinic', 'Clinic'), ('camp', 'Camp'), ('seasonal', 'Seasonal Package'), ('pickup', 'Pick Up Game'), ('tryout', 'Tryout'), ('tournament', 'Tournament'), ('select_practice', 'APC Select Practice'), ('select_game', 'APC Select Game')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='SelectGameRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'No Response'), ('coming', 'Coming'), ('not_coming', 'Not Coming')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rsvps', to='clients.client')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='bookings.selectgame')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_rsvps', to='clients.player')),
            ],
            options={
                'ordering': ['game', 'client'],
                'indexes': [models.Index(fields=['client', 'status'], name='bookings_se_client__71bdc4_idx'), models.Index(fields=['game', 'status'], name='bookings_se_game_id_8e38c9_idx')],
                'unique_together': {('game', 'client')},
            },
        ),
        migrations.AddIndex(
            model_name='selectgame',
            index=models.Index(fields=['team', 'date'], name='bookings_se_team_id_404f92_idx'),
        ),
        migrations.AddIndex(
            model_name='selectgame',
            index=models.Index(fields=['status', 'date'], name='bookings_se_status_6d86de_idx'),
        ),
    ]
